### ISSUE TITLE
% Representation

### ISSUE THREAD

**Issue by nrsulliv** [aajfranklin/Click-And-Roll#29]
Minor gripe, but under FG%, the number shown is a decimal, leading percentages to look 100x lower than they actually are. I propose the stat table to show FG% as either true percentage, e.g., 53%, or as a fraction, .53. But not both. Hope this makes sense

**Comment by aajfranklin** [comment]
Just so I'm clear: you would prefer .532 over 0.532? I agree and will include in the next release.

**Comment by nrsulliv** [comment]
Yeah! Or have 53.2% in the table. Love your work btw

**Comment by nrsulliv** [comment]
I meant more like that currently it implies .532% instead of 53.2%. If that
makes sense.

**Comment by aajfranklin** [comment]
Yeah I understand. I think I prefer .532 over 53.2%, just to be consistent with existing sites like basketball reference, which I consider the standard. It's definitely clearer without the leading zero. Thanks for bringing it to my attention!

**Comment by nrsulliv** [comment]
Ah makes total sense. Cheers! Yeah, the leading zero is what caused the
implication. Thanks again for building this. So dope.

**Comment by aajfranklin** [comment]
Included in 1.2.0, which has been submitted to the chrome store and is pending review
