### ISSUE TITLE
Re-order stats so that PTS, REB, AST, BLK, STL are visible without scrolling on most monitors

### ISSUE THREAD

**Issue by maxguthmann** [aajfranklin/Click-And-Roll#30]
Points are probably the most important counting stat. They should be between min and FGM. hovering over the name and clicking outside the box to close the window is the perfect ux, but having to scroll horizontally causes some disruption to browsing activity. Might be nice if we could customize the categories we see too.

Thanks for the work you've put into this.

**Comment by aajfranklin** [comment]
Thanks for the suggestion! This has come up a lot. I plan to move PTS, REB, AST, BLK, STL further to the left so they are all viewable without scrolling, pushing some of the shooting % stats over to the right.

**Comment by aajfranklin** [comment]
Included in 1.2.0, which has been submitted to the chrome store and is pending review
