### ISSUE TITLE
Settings toggle to inverse row order

### ISSUE THREAD

**Issue by maxguthmann** [aajfranklin/Click-And-Roll#31]
It would be better to have the first row career stats and have rows below be yearly stats counting backwards. I believe most use cases only care for career stats and most recent season or two.

**Comment by aajfranklin** [comment]
Thanks for the suggestion. This came up occasionally on Reddit also. I will include an option in the settings to reverse the order of the rows.

**Comment by aajfranklin** [comment]
Included in 1.2.0 as a toggle to reverse career rows. 1.2.0 has been submitted to the chrome store and is pending review
