### ISSUE TITLE
Option for click-and-roll to be disabled by default and enabled on a per-site basis, with view- and edit-able white/blacklist

### ISSUE THREAD

**Issue by aksrikanth** [aajfranklin/Click-And-Roll#47]
Also please let us look at and modify the allowed/disallowed sites and edit them in the options.

**Comment by aajfranklin** [comment]
This is a good suggestion and I intend to implement it for the next release.

**Comment by aajfranklin** [comment]
This feature is included in version 2.1.0, which has been submitted to each browser's store and is pending approval.
