### ISSUE TITLE
Click-and-roll is very slow in Firefox.

### ISSUE THREAD

**Issue by aksrikanth** [aajfranklin/Click-And-Roll#48]
It takes multiple seconds to highlight names (up to 20 seconds sometimes).

This is with latest firefox (v75.0) on Mac

**Comment by aajfranklin** [comment]
I have also noticed that click and roll takes longer to kick in on firefox. I think this is to do with when Firefox fires it's 'onload' event possibly being later than other browsers, but that's just a hunch. I will investigate and optimise if I can.

**Comment by aajfranklin** [comment]
As of 2.1.0, click and roll starts earlier in the page load process and should be quicker in Firefox as a result. 2.1.0 has been submitted to each browser's store and is pending approval.
