### ISSUE TITLE
Bug: Out-dated data

### ISSUE THREAD

**Issue by jammcc** [aajfranklin/Click-And-Roll#53]
I have tested on a couple devices, all on Chrome. It seems that data stopped updating towards the end of the season:
![image](https://user-images.githubusercontent.com/4643039/120010500-371ea480-bfab-11eb-8b2c-c1453f911f3e.png)

Note 67 games played in the regular season rather than 72.

**Comment by aajfranklin** [comment]
Hey, thanks for alerting me. I've noticed this recently too.

The click and roll server is hosted on AWS, but the I update the stats with a periodic job running on a local machine that then pushes the new data to the cloud. This helps get around some NBA api restrictions.

I suspect that local machine may have had a network issue and can't post the new data to the cloud. I'm away from that machine at the moment so can't verify. But I will do my best to get this fixed shortly.

**Comment by aajfranklin** [comment]
@jammcc This is now fixed. If you see any out of date data now, it is probably because the extension caches recently viewed players for a short time, to reduce requests to the server. Thanks for raising this.
